services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: signo-tech-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=signo-tech
    volumes:
      - pgdata:/bitnami/postgresql
      # Adicione esta linha abaixo:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  pgdata:
